INSERT INTO `opening_schedule` (`friday`,`monday`,`saturday`,`sunday`,`thursday`)
VALUES
  ("08-12,13-15,18-21","00-03,06-12","09-17","21-23","12-15,20-22"),
  ("08-12,13-15,18-21","00-03,06-12","09-17","21-23","12-15,20-22"),
  ("08-12,13-15,18-21","00-03,06-12","09-17","21-23","12-15,20-22"),
  ("08-12,13-15,18-21","00-03,06-12","09-17","21-23","12-15,20-22"),
  ("08-12,13-15,18-21","00-03,06-12","09-17","21-23","12-15,20-22"),
  ("08-12,13-15,18-21","00-03,06-12","09-17","21-23","12-15,20-22"),
  ("08-12,13-15,18-21","00-03,06-12","09-17","21-23","12-15,20-22"),
  ("08-12,13-15,18-21","00-03,06-12","09-17","21-23","12-15,20-22"),
  ("08-12,13-15,18-21","00-03,06-12","09-17","21-23","12-15,20-22"),
  ("08-12,13-15,18-21","00-03,06-12","09-17","21-23","12-15,20-22");


insert into shop (category_count, product_count, closed, creation_date, name, schedule_id) values (40, 40, false, '2017-06-15 07:10:08', 'Fiveclub', 1);
insert into shop (category_count, product_count, closed, creation_date, name, schedule_id) values (27, 7, true, '2020-12-15 21:04:13', 'Meejo', 2);
insert into shop (category_count, product_count, closed, creation_date, name, schedule_id) values (52, 99, false, '2020-05-07 01:57:46', 'Blogtags', 3);
insert into shop (category_count, product_count, closed, creation_date, name, schedule_id) values (39, 71, false, '2021-08-16 15:02:33', 'Dabtype', 4);
insert into shop (category_count, product_count, closed, creation_date, name, schedule_id) values (71, 17, false, '2018-02-23 19:43:04', 'Topiczoom', 5);
insert into shop (category_count, product_count, closed, creation_date, name, schedule_id) values (13, 16, false, '2022-12-28 23:13:51', 'Twitternation', 6);
insert into shop (category_count, product_count, closed, creation_date, name, schedule_id) values (72, 77, false, '2022-08-20 22:25:07', 'Zoombox', 7);
insert into shop (category_count, product_count, closed, creation_date, name, schedule_id) values (16, 50, false, '2021-04-30 10:44:52', 'Yodo', 8);
insert into shop (category_count, product_count, closed, creation_date, name, schedule_id) values (20, 30, true, '2017-07-02 01:53:44', 'Skibox', 9);
insert into shop (category_count, product_count, closed, creation_date, name, schedule_id) values (80, 99, true, '2020-03-31 15:11:46', 'Wikido', 10);

insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Conardia Moss', 'Amblystegiaceae', 'vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy', 'erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer', 63.53, 7);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Napa Cryptantha', 'Boraginaceae', 'non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 'sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue', 2.79, 7);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Parry''s Rabbitbrush', 'Asteraceae', 'ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at', 'dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non', 49.06, 5);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Coastal Sweetpepperbush', 'Clethraceae', 'rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam', 'condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt', 22.75, 9);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Shrubby Willowherb', 'Onagraceae', 'dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes', 'nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu', 76.44, 7);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Pandanus', 'Pandanaceae', 'ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis', 'mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut', 55.55, 6);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Wattapama', 'Fabaceae', 'potenti in eleifend quam a odio in hac habitasse platea', 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue', 46.07, 10);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Hygrohypnum Moss', 'Amblystegiaceae', 'nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis', 'quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin', 20.0, 5);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Texas Crab Apple', 'Rosaceae', 'suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur', 'at nibh in hac habitasse platea dictumst aliquam augue quam', 36.68, 6);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Japanese Snowbell', 'Styracaceae', 'diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris', 'duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis', 57.33, 1);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Parry''s Dwarf-sunflower', 'Asteraceae', 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna', 'ligula nec sem duis aliquam convallis nunc proin at turpis a pede', 13.4, 6);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Alpine Sagebrush', 'Asteraceae', 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue', 'orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi', 57.67, 10);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Doum Palm', 'Arecaceae', 'ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non', 'posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut', 2.66, 3);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Precocious Milkvetch', 'Fabaceae', 'congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed', 'consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo', 7.01, 6);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Owlfruit Sedge', 'Cyperaceae', 'sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor', 'eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus', 91.36, 8);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Jacob''s-ladder', 'Polemoniaceae', 'pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus', 'libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim', 82.68, 7);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Shortleaf Wild Coffee', 'Rubiaceae', 'facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt', 'duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede', 25.94, 10);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Polynesian Peperomia', 'Piperaceae', 'nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed', 'curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin', 1.71, 6);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Cup Lichen', 'Cladoniaceae', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate', 'a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla', 26.98, 7);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Loquat', 'Rosaceae', 'quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a', 'pretium iaculis justo in hac habitasse platea dictumst etiam faucibus', 88.3, 1);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Yellow Monardella', 'Lamiaceae', 'quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus', 'quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus', 48.43, 2);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Ophir Pass Rockcress', 'Brassicaceae', 'et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet', 'id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci', 34.29, 6);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Smilograss', 'Poaceae', 'vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere', 'dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat', 47.47, 10);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Bolivian Walnut', 'Juglandaceae', 'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo', 'convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et', 62.64, 3);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Scouler''s Willow', 'Salicaceae', 'curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum', 'vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla', 31.23, 7);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Plains Muhly', 'Poaceae', 'mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor', 'eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum', 95.75, 3);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Pincushion', 'Asteraceae', 'a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi', 'sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus', 66.45, 4);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Pinkladies', 'Onagraceae', 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at', 'justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis', 31.12, 4);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Bluntleaf Pondweed', 'Potamogetonaceae', 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est', 'mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non', 54.19, 5);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Gentian', 'Gentianaceae', 'nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo', 'tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien', 50.56, 5);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Dwarf Hackberry', 'Ulmaceae', 'eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus', 'lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec', 49.0, 4);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Yellow And White Monkeyflower', 'Scrophulariaceae', 'vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec', 'interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis', 72.33, 3);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Trans-pecos Tansyaster', 'Asteraceae', 'ut erat id mauris vulputate elementum nullam varius nulla facilisi cras', 'in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at', 11.25, 2);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Monkswort', 'Boraginaceae', 'pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat', 'erat eros viverra eget congue eget semper rutrum nulla nunc purus', 78.0, 6);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Tree Cholla', 'Cactaceae', 'magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus', 'amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at', 7.97, 4);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Japanese Apricot', 'Rosaceae', 'vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci', 'potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum', 15.76, 2);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Metallic Taro', 'Araceae', 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros', 'diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue', 77.29, 4);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Paradox Sunflower', 'Asteraceae', 'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit', 'lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in', 84.07, 7);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Dwarf Nasturtium', 'Tropaeolaceae', 'maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui', 'massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst', 93.48, 2);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Wavyleaf Thistle', 'Asteraceae', 'posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor', 'nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor', 41.41, 2);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Bejuco De Masa', 'Boraginaceae', 'vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer', 'dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis', 86.11, 3);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Yellowdot Saxifrage', 'Saxifragaceae', 'in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit', 'lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in', 72.26, 10);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Brazilian Bayhops', 'Convolvulaceae', 'lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat', 'eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio', 38.73, 3);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Gray''s Draba', 'Brassicaceae', 'tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus', 'ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis', 63.78, 10);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('California Bedstraw', 'Rubiaceae', 'sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper', 'integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue', 38.83, 3);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Foamflower', 'Saxifragaceae', 'nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac', 'volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac', 3.95, 9);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Iwarancusa Grass', 'Poaceae', 'vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit', 'odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est', 65.07, 4);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('San Gabriel Ragwort', 'Asteraceae', 'est risus auctor sed tristique in tempus sit amet sem fusce consequat', 'est risus auctor sed tristique in tempus sit amet sem fusce', 52.82, 8);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Alabama Hawthorn', 'Rosaceae', 'ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt', 'nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam', 53.73, 9);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Screwleaf Muhly', 'Poaceae', 'a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio', 'sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac', 13.01, 3);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Platygyrium Moss', 'Hypnaceae', 'pede justo eu massa donec dapibus duis at velit eu est congue elementum in', 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam', 44.04, 2);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('California Sclerophyton Lichen', 'Opegraphaceae', 'in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam', 'et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel', 51.17, 10);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Matted Lichen', 'Pannariaceae', 'erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat', 68.27, 2);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Hedge False Bindweed', 'Convolvulaceae', 'ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec', 'volutpat in congue etiam justo etiam pretium iaculis justo in', 24.28, 9);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Mountain Fishscale Lichen', 'Psoraceae', 'amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla', 'ut ultrices vel augue vestibulum ante ipsum primis in faucibus', 57.38, 5);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Caroline Ivory Nutpalm', 'Arecaceae', 'sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum', 'in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla', 27.06, 6);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Chapman''s Butterwort', 'Lentibulariaceae', 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis', 'curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel', 3.87, 6);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Waikamoi Peperomia', 'Piperaceae', 'eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo', 'nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus', 32.04, 1);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Carrion-flower', 'Asclepiadaceae', 'lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer', 'curae nulla dapibus dolor vel est donec odio justo sollicitudin ut', 66.56, 7);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Bauhinia', 'Fabaceae', 'blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus', 'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc', 14.78, 3);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Arizona Bluehearts', 'Scrophulariaceae', 'nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst', 'mattis egestas metus aenean fermentum donec ut mauris eget massa tempor', 80.9, 8);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Roundfruit Sedge', 'Cyperaceae', 'phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl', 'morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate', 73.22, 3);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Miniature Marigold', 'Asteraceae', 'sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu pede', 'in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi', 96.26, 6);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Shortstem Beardtongue', 'Scrophulariaceae', 'nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at', 'morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce', 92.26, 4);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Fineleaf Pondweed', 'Potamogetonaceae', 'sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh', 'egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla', 45.6, 2);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Tiburon Mariposa Lily', 'Liliaceae', 'fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse', 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac', 84.03, 10);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Bigleaf Mistletoe', 'Viscaceae', 'ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend', 'odio cras mi pede malesuada in imperdiet et commodo vulputate justo in', 77.29, 9);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Lloyd''s Fishhook Cactus', 'Cactaceae', 'eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus', 'lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet', 63.75, 10);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('California Rim Lichen', 'Lecanoraceae', 'aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi', 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem', 52.97, 5);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Cup Lichen', 'Cladoniaceae', 'molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient', 'ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus', 27.81, 2);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Showy Indian Clover', 'Fabaceae', 'sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula', 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan', 25.92, 9);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Florida Poisontree', 'Anacardiaceae', 'sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede', 'porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id', 84.34, 4);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Q-tips', 'Asteraceae', 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia', 'vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis', 83.3, 10);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Curvepod Yellowcress', 'Brassicaceae', 'primis in faucibus orci luctus et ultrices posuere cubilia curae', 'dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum', 83.15, 4);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Media Sandspurry', 'Caryophyllaceae', 'id consequat in consequat ut nulla sed accumsan felis ut at', 'cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris', 84.24, 4);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Tropic Daisy', 'Asteraceae', 'maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus', 'tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc', 18.11, 5);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Creeping Spleenwort', 'Aspleniaceae', 'tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor', 'duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo', 6.55, 8);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Hybrid Hickory', 'Juglandaceae', 'aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio', 'odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est', 58.39, 2);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Variegated Phlox', 'Polemoniaceae', 'rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat', 'erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget', 60.67, 7);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('San Luis Obispo Serpentine Dudleya', 'Crassulaceae', 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan', 'pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus', 73.56, 9);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Arctic Cottongrass', 'Cyperaceae', 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut', 'vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia', 73.97, 6);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Geno Geno', 'Fabaceae', 'dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis', 'aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus', 41.54, 9);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Summer Grape', 'Vitaceae', 'odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum', 'morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim', 88.12, 1);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Elegant Buckwheat', 'Polygonaceae', 'pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a', 'in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non', 52.58, 5);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Spreading Groundsmoke', 'Onagraceae', 'nec dui luctus rutrum nulla tellus in sagittis dui vel', 'adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in', 13.05, 1);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Purple Coneflower', 'Asteraceae', 'in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id', 'duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris', 3.28, 2);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Coco Yam', 'Araceae', 'mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus', 'at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel', 45.83, 1);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Plains Muhly', 'Poaceae', 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu', 'donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante', 88.97, 4);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Gilman''s Buckwheat', 'Polygonaceae', 'primis in faucibus orci luctus et ultrices posuere cubilia curae donec', 'at velit eu est congue elementum in hac habitasse platea dictumst morbi', 43.55, 6);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Myrtleleaf St. Johnswort', 'Clusiaceae', 'luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra', 'vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 73.56, 3);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('California False Indigo', 'Fabaceae', 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor', 'ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in', 53.39, 10);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Klamath Manzanita', 'Ericaceae', 'eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id', 'odio donec vitae nisi nam ultrices libero non mattis pulvinar', 59.2, 8);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Plagiomnium Moss', 'Mniaceae', 'ligula nec sem duis aliquam convallis nunc proin at turpis a pede', 'etiam faucibus cursus urna ut tellus nulla ut erat id mauris', 84.35, 3);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Long-stolon Sedge', 'Cyperaceae', 'posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 'amet cursus id turpis integer aliquet massa id lobortis convallis tortor', 39.42, 10);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Diplotomma Lichen', 'Physciaceae', 'neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan', 'pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 56.89, 9);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Rydberg''s Golden Columbine', 'Ranunculaceae', 'nulla nunc purus phasellus in felis donec semper sapien a libero nam', 'nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', 84.73, 3);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Anzia Lichen', 'Parmeliaceae', 'aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit', 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean', 42.26, 10);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Sky Lupine', 'Fabaceae', 'tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa', 'in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla', 77.46, 6);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Schweinitz''s Dotted Lichen', 'Bacidiaceae', 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in', 'lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 6.77, 1);
insert into product (namefr, nameeng, descriptionfr, descriptioneng, price, shop_id) values ('Carnauba Wax Palm', 'Arecaceae', 'enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis', 'curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est', 33.15, 3);


insert into category (name, product_id) values ('Accounting', 100);
insert into category (name, product_id) values ('Legal', 55);
insert into category (name, product_id) values ('Legal', 98);
insert into category (name, product_id) values ('Services', 92);
insert into category (name, product_id) values ('Engineering', 35);
insert into category (name, product_id) values ('Product Management', 47);
insert into category (name, product_id) values ('Marketing', 96);
insert into category (name, product_id) values ('Services', 69);
insert into category (name, product_id) values ('Engineering', 25);
insert into category (name, product_id) values ('Product Management', 4);
insert into category (name, product_id) values ('Engineering', 98);
insert into category (name, product_id) values ('Marketing', 63);
insert into category (name, product_id) values ('Human Resources', 73);
insert into category (name, product_id) values ('Business Development', 63);
insert into category (name, product_id) values ('Support', 28);
insert into category (name, product_id) values ('Services', 19);
insert into category (name, product_id) values ('Services', 15);
insert into category (name, product_id) values ('Sales', 57);
insert into category (name, product_id) values ('Services', 5);
insert into category (name, product_id) values ('Engineering', 92);
insert into category (name, product_id) values ('Product Management', 79);
insert into category (name, product_id) values ('Training', 53);
insert into category (name, product_id) values ('Business Development', 4);
insert into category (name, product_id) values ('Services', 68);
insert into category (name, product_id) values ('Engineering', 92);
insert into category (name, product_id) values ('Legal', 43);
insert into category (name, product_id) values ('Human Resources', 31);
insert into category (name, product_id) values ('Accounting', 41);
insert into category (name, product_id) values ('Marketing', 62);
insert into category (name, product_id) values ('Human Resources', 26);
insert into category (name, product_id) values ('Marketing', 94);
insert into category (name, product_id) values ('Product Management', 62);
insert into category (name, product_id) values ('Training', 28);
insert into category (name, product_id) values ('Support', 87);
insert into category (name, product_id) values ('Support', 21);
insert into category (name, product_id) values ('Support', 85);
insert into category (name, product_id) values ('Product Management', 58);
insert into category (name, product_id) values ('Product Management', 17);
insert into category (name, product_id) values ('Research and Development', 51);
insert into category (name, product_id) values ('Accounting', 4);
insert into category (name, product_id) values ('Support', 44);
insert into category (name, product_id) values ('Support', 59);
insert into category (name, product_id) values ('Marketing', 32);
insert into category (name, product_id) values ('Accounting', 57);
insert into category (name, product_id) values ('Engineering', 2);
insert into category (name, product_id) values ('Sales', 10);
insert into category (name, product_id) values ('Sales', 5);
insert into category (name, product_id) values ('Research and Development', 23);
insert into category (name, product_id) values ('Legal', 88);
insert into category (name, product_id) values ('Human Resources', 52);
insert into category (name, product_id) values ('Business Development', 49);
insert into category (name, product_id) values ('Engineering', 22);
insert into category (name, product_id) values ('Product Management', 5);
insert into category (name, product_id) values ('Research and Development', 46);
insert into category (name, product_id) values ('Training', 61);
insert into category (name, product_id) values ('Business Development', 28);
insert into category (name, product_id) values ('Marketing', 98);
insert into category (name, product_id) values ('Marketing', 31);
insert into category (name, product_id) values ('Sales', 89);
insert into category (name, product_id) values ('Engineering', 53);
insert into category (name, product_id) values ('Accounting', 41);
insert into category (name, product_id) values ('Marketing', 33);
insert into category (name, product_id) values ('Sales', 86);
insert into category (name, product_id) values ('Training', 94);
insert into category (name, product_id) values ('Sales', 64);
insert into category (name, product_id) values ('Sales', 96);
insert into category (name, product_id) values ('Research and Development', 8);
insert into category (name, product_id) values ('Support', 27);
insert into category (name, product_id) values ('Product Management', 49);
insert into category (name, product_id) values ('Human Resources', 18);
insert into category (name, product_id) values ('Business Development', 17);
insert into category (name, product_id) values ('Business Development', 79);
insert into category (name, product_id) values ('Human Resources', 14);
insert into category (name, product_id) values ('Legal', 21);
insert into category (name, product_id) values ('Product Management', 11);
insert into category (name, product_id) values ('Accounting', 75);
insert into category (name, product_id) values ('Human Resources', 32);
insert into category (name, product_id) values ('Product Management', 6);
insert into category (name, product_id) values ('Research and Development', 74);
insert into category (name, product_id) values ('Accounting', 96);
insert into category (name, product_id) values ('Support', 49);
insert into category (name, product_id) values ('Accounting', 95);
insert into category (name, product_id) values ('Accounting', 46);
insert into category (name, product_id) values ('Accounting', 32);
insert into category (name, product_id) values ('Legal', 50);
insert into category (name, product_id) values ('Human Resources', 78);
insert into category (name, product_id) values ('Sales', 73);
insert into category (name, product_id) values ('Sales', 52);
insert into category (name, product_id) values ('Human Resources', 56);
insert into category (name, product_id) values ('Sales', 99);
insert into category (name, product_id) values ('Engineering', 40);
insert into category (name, product_id) values ('Human Resources', 13);
insert into category (name, product_id) values ('Services', 43);
insert into category (name, product_id) values ('Product Management', 66);
insert into category (name, product_id) values ('Support', 70);
insert into category (name, product_id) values ('Accounting', 15);
insert into category (name, product_id) values ('Accounting', 14);
insert into category (name, product_id) values ('Human Resources', 31);
insert into category (name, product_id) values ('Legal', 86);
insert into category (name, product_id) values ('Human Resources', 59);
insert into category (name, product_id) values ('Services', 6);
insert into category (name, product_id) values ('Training', 5);
insert into category (name, product_id) values ('Marketing', 68);
insert into category (name, product_id) values ('Accounting', 74);
insert into category (name, product_id) values ('Human Resources', 47);
insert into category (name, product_id) values ('Business Development', 6);
insert into category (name, product_id) values ('Business Development', 24);
insert into category (name, product_id) values ('Marketing', 72);
insert into category (name, product_id) values ('Legal', 5);
insert into category (name, product_id) values ('Services', 78);
insert into category (name, product_id) values ('Sales', 19);
insert into category (name, product_id) values ('Support', 89);
insert into category (name, product_id) values ('Engineering', 79);
insert into category (name, product_id) values ('Training', 33);
insert into category (name, product_id) values ('Sales', 35);
insert into category (name, product_id) values ('Business Development', 20);
insert into category (name, product_id) values ('Human Resources', 6);
insert into category (name, product_id) values ('Support', 23);
insert into category (name, product_id) values ('Support', 28);
insert into category (name, product_id) values ('Support', 37);
insert into category (name, product_id) values ('Sales', 31);
insert into category (name, product_id) values ('Marketing', 93);
insert into category (name, product_id) values ('Product Management', 1);
insert into category (name, product_id) values ('Sales', 36);
insert into category (name, product_id) values ('Product Management', 82);
insert into category (name, product_id) values ('Accounting', 61);
insert into category (name, product_id) values ('Product Management', 44);
insert into category (name, product_id) values ('Training', 1);
insert into category (name, product_id) values ('Human Resources', 23);
insert into category (name, product_id) values ('Marketing', 34);
insert into category (name, product_id) values ('Research and Development', 46);
insert into category (name, product_id) values ('Engineering', 36);
insert into category (name, product_id) values ('Training', 70);
insert into category (name, product_id) values ('Legal', 72);
insert into category (name, product_id) values ('Training', 47);
insert into category (name, product_id) values ('Human Resources', 10);
insert into category (name, product_id) values ('Support', 39);
insert into category (name, product_id) values ('Research and Development', 22);
insert into category (name, product_id) values ('Training', 2);
insert into category (name, product_id) values ('Training', 2);
insert into category (name, product_id) values ('Legal', 56);
insert into category (name, product_id) values ('Training', 93);
insert into category (name, product_id) values ('Research and Development', 95);
insert into category (name, product_id) values ('Legal', 79);
insert into category (name, product_id) values ('Engineering', 21);
insert into category (name, product_id) values ('Engineering', 8);
insert into category (name, product_id) values ('Engineering', 89);
insert into category (name, product_id) values ('Support', 7);
insert into category (name, product_id) values ('Product Management', 82);
insert into category (name, product_id) values ('Legal', 59);
insert into category (name, product_id) values ('Marketing', 97);
insert into category (name, product_id) values ('Services', 29);
insert into category (name, product_id) values ('Legal', 55);
insert into category (name, product_id) values ('Sales', 78);
insert into category (name, product_id) values ('Product Management', 65);
insert into category (name, product_id) values ('Human Resources', 94);
insert into category (name, product_id) values ('Engineering', 46);
insert into category (name, product_id) values ('Engineering', 85);
insert into category (name, product_id) values ('Human Resources', 71);
insert into category (name, product_id) values ('Marketing', 66);
insert into category (name, product_id) values ('Business Development', 63);
insert into category (name, product_id) values ('Services', 4);
insert into category (name, product_id) values ('Sales', 8);
insert into category (name, product_id) values ('Legal', 85);
insert into category (name, product_id) values ('Training', 66);
insert into category (name, product_id) values ('Legal', 16);
insert into category (name, product_id) values ('Training', 62);
insert into category (name, product_id) values ('Business Development', 32);
insert into category (name, product_id) values ('Marketing', 81);
insert into category (name, product_id) values ('Services', 63);
insert into category (name, product_id) values ('Research and Development', 83);
insert into category (name, product_id) values ('Product Management', 74);
insert into category (name, product_id) values ('Business Development', 81);
insert into category (name, product_id) values ('Accounting', 41);
insert into category (name, product_id) values ('Business Development', 1);
insert into category (name, product_id) values ('Product Management', 62);
insert into category (name, product_id) values ('Services', 47);
insert into category (name, product_id) values ('Support', 93);
insert into category (name, product_id) values ('Sales', 46);
insert into category (name, product_id) values ('Business Development', 55);
insert into category (name, product_id) values ('Legal', 34);
insert into category (name, product_id) values ('Business Development', 66);
insert into category (name, product_id) values ('Accounting', 69);
insert into category (name, product_id) values ('Research and Development', 71);
insert into category (name, product_id) values ('Training', 12);
insert into category (name, product_id) values ('Sales', 80);
insert into category (name, product_id) values ('Marketing', 52);
insert into category (name, product_id) values ('Marketing', 42);
insert into category (name, product_id) values ('Research and Development', 68);
insert into category (name, product_id) values ('Business Development', 5);
insert into category (name, product_id) values ('Engineering', 57);
insert into category (name, product_id) values ('Sales', 72);
insert into category (name, product_id) values ('Engineering', 27);
insert into category (name, product_id) values ('Business Development', 32);
insert into category (name, product_id) values ('Research and Development', 3);
insert into category (name, product_id) values ('Legal', 82);
insert into category (name, product_id) values ('Engineering', 45);
insert into category (name, product_id) values ('Accounting', 9);
insert into category (name, product_id) values ('Product Management', 57);
insert into category (name, product_id) values ('Research and Development', 87);
insert into category (name, product_id) values ('Support', 67);
insert into category (name, product_id) values ('Marketing', 40);
insert into category (name, product_id) values ('Marketing', 79);
insert into category (name, product_id) values ('Human Resources', 29);
insert into category (name, product_id) values ('Legal', 2);
insert into category (name, product_id) values ('Training', 59);
insert into category (name, product_id) values ('Engineering', 18);
insert into category (name, product_id) values ('Marketing', 71);
insert into category (name, product_id) values ('Legal', 47);
insert into category (name, product_id) values ('Services', 83);
insert into category (name, product_id) values ('Business Development', 43);
insert into category (name, product_id) values ('Product Management', 87);
insert into category (name, product_id) values ('Legal', 21);
insert into category (name, product_id) values ('Services', 57);
insert into category (name, product_id) values ('Human Resources', 47);
insert into category (name, product_id) values ('Training', 42);
insert into category (name, product_id) values ('Product Management', 28);
insert into category (name, product_id) values ('Training', 36);
insert into category (name, product_id) values ('Legal', 47);
insert into category (name, product_id) values ('Support', 46);
insert into category (name, product_id) values ('Product Management', 52);
insert into category (name, product_id) values ('Research and Development', 40);
insert into category (name, product_id) values ('Research and Development', 49);
insert into category (name, product_id) values ('Marketing', 49);
insert into category (name, product_id) values ('Marketing', 87);
insert into category (name, product_id) values ('Research and Development', 44);
insert into category (name, product_id) values ('Product Management', 81);
insert into category (name, product_id) values ('Accounting', 78);
insert into category (name, product_id) values ('Human Resources', 95);
insert into category (name, product_id) values ('Product Management', 72);
insert into category (name, product_id) values ('Product Management', 78);
insert into category (name, product_id) values ('Human Resources', 15);
insert into category (name, product_id) values ('Engineering', 90);
insert into category (name, product_id) values ('Engineering', 89);
insert into category (name, product_id) values ('Human Resources', 77);
insert into category (name, product_id) values ('Human Resources', 20);
insert into category (name, product_id) values ('Training', 73);
insert into category (name, product_id) values ('Support', 76);
insert into category (name, product_id) values ('Product Management', 98);
insert into category (name, product_id) values ('Support', 52);
insert into category (name, product_id) values ('Legal', 12);
insert into category (name, product_id) values ('Legal', 18);
insert into category (name, product_id) values ('Legal', 46);
insert into category (name, product_id) values ('Support', 1);
insert into category (name, product_id) values ('Accounting', 15);
insert into category (name, product_id) values ('Support', 31);
insert into category (name, product_id) values ('Legal', 54);
insert into category (name, product_id) values ('Product Management', 24);
insert into category (name, product_id) values ('Accounting', 96);
insert into category (name, product_id) values ('Product Management', 2);
insert into category (name, product_id) values ('Sales', 67);
insert into category (name, product_id) values ('Product Management', 51);
insert into category (name, product_id) values ('Engineering', 97);
insert into category (name, product_id) values ('Human Resources', 91);
insert into category (name, product_id) values ('Services', 28);
insert into category (name, product_id) values ('Business Development', 73);
insert into category (name, product_id) values ('Research and Development', 67);
insert into category (name, product_id) values ('Business Development', 38);
insert into category (name, product_id) values ('Services', 3);
insert into category (name, product_id) values ('Engineering', 89);
insert into category (name, product_id) values ('Engineering', 64);
insert into category (name, product_id) values ('Business Development', 76);
insert into category (name, product_id) values ('Sales', 48);
insert into category (name, product_id) values ('Human Resources', 59);
insert into category (name, product_id) values ('Legal', 88);
insert into category (name, product_id) values ('Human Resources', 51);
insert into category (name, product_id) values ('Research and Development', 56);
insert into category (name, product_id) values ('Sales', 26);
insert into category (name, product_id) values ('Sales', 13);
insert into category (name, product_id) values ('Marketing', 3);
insert into category (name, product_id) values ('Business Development', 96);
insert into category (name, product_id) values ('Services', 10);
insert into category (name, product_id) values ('Product Management', 17);
insert into category (name, product_id) values ('Product Management', 4);
insert into category (name, product_id) values ('Marketing', 10);
insert into category (name, product_id) values ('Business Development', 40);
insert into category (name, product_id) values ('Sales', 29);
insert into category (name, product_id) values ('Business Development', 84);
insert into category (name, product_id) values ('Accounting', 65);
insert into category (name, product_id) values ('Sales', 37);
insert into category (name, product_id) values ('Marketing', 27);
insert into category (name, product_id) values ('Sales', 35);
insert into category (name, product_id) values ('Business Development', 88);
insert into category (name, product_id) values ('Human Resources', 53);
insert into category (name, product_id) values ('Business Development', 38);
insert into category (name, product_id) values ('Product Management', 53);
insert into category (name, product_id) values ('Marketing', 76);
insert into category (name, product_id) values ('Support', 71);
insert into category (name, product_id) values ('Human Resources', 11);
insert into category (name, product_id) values ('Services', 78);
insert into category (name, product_id) values ('Product Management', 11);
insert into category (name, product_id) values ('Accounting', 68);
insert into category (name, product_id) values ('Marketing', 64);
insert into category (name, product_id) values ('Services', 51);
insert into category (name, product_id) values ('Services', 86);
insert into category (name, product_id) values ('Business Development', 11);
insert into category (name, product_id) values ('Sales', 7);
insert into category (name, product_id) values ('Sales', 91);
insert into category (name, product_id) values ('Marketing', 85);
insert into category (name, product_id) values ('Training', 99);
insert into category (name, product_id) values ('Engineering', 81);
insert into category (name, product_id) values ('Support', 32);
insert into category (name, product_id) values ('Marketing', 4);
insert into category (name, product_id) values ('Business Development', 64);
insert into category (name, product_id) values ('Product Management', 35);
insert into category (name, product_id) values ('Sales', 98);
insert into category (name, product_id) values ('Human Resources', 56);
insert into category (name, product_id) values ('Sales', 8);
insert into category (name, product_id) values ('Marketing', 89);
insert into category (name, product_id) values ('Human Resources', 46);
insert into category (name, product_id) values ('Business Development', 97);
insert into category (name, product_id) values ('Support', 53);
insert into category (name, product_id) values ('Human Resources', 53);
insert into category (name, product_id) values ('Product Management', 64);
insert into category (name, product_id) values ('Services', 11);
insert into category (name, product_id) values ('Marketing', 35);
insert into category (name, product_id) values ('Accounting', 67);
insert into category (name, product_id) values ('Accounting', 13);
insert into category (name, product_id) values ('Sales', 79);
insert into category (name, product_id) values ('Engineering', 23);
insert into category (name, product_id) values ('Marketing', 36);
insert into category (name, product_id) values ('Accounting', 59);
insert into category (name, product_id) values ('Services', 48);
insert into category (name, product_id) values ('Marketing', 53);
insert into category (name, product_id) values ('Marketing', 97);
insert into category (name, product_id) values ('Sales', 27);
insert into category (name, product_id) values ('Research and Development', 92);
insert into category (name, product_id) values ('Accounting', 99);
insert into category (name, product_id) values ('Sales', 33);
insert into category (name, product_id) values ('Marketing', 19);
insert into category (name, product_id) values ('Services', 41);
insert into category (name, product_id) values ('Human Resources', 42);
insert into category (name, product_id) values ('Marketing', 22);
insert into category (name, product_id) values ('Research and Development', 29);
insert into category (name, product_id) values ('Marketing', 1);
insert into category (name, product_id) values ('Sales', 54);
insert into category (name, product_id) values ('Product Management', 70);
insert into category (name, product_id) values ('Marketing', 78);
insert into category (name, product_id) values ('Research and Development', 69);
insert into category (name, product_id) values ('Support', 2);
insert into category (name, product_id) values ('Product Management', 4);
insert into category (name, product_id) values ('Legal', 1);
insert into category (name, product_id) values ('Support', 4);
insert into category (name, product_id) values ('Legal', 44);
insert into category (name, product_id) values ('Human Resources', 55);
insert into category (name, product_id) values ('Business Development', 14);
insert into category (name, product_id) values ('Support', 94);
insert into category (name, product_id) values ('Legal', 78);
insert into category (name, product_id) values ('Services', 12);
insert into category (name, product_id) values ('Marketing', 15);
insert into category (name, product_id) values ('Product Management', 94);
insert into category (name, product_id) values ('Engineering', 12);
insert into category (name, product_id) values ('Accounting', 15);
insert into category (name, product_id) values ('Accounting', 73);
insert into category (name, product_id) values ('Business Development', 32);
insert into category (name, product_id) values ('Sales', 63);
insert into category (name, product_id) values ('Accounting', 2);
insert into category (name, product_id) values ('Accounting', 97);
insert into category (name, product_id) values ('Research and Development', 90);
insert into category (name, product_id) values ('Services', 3);
insert into category (name, product_id) values ('Engineering', 39);
insert into category (name, product_id) values ('Business Development', 2);
insert into category (name, product_id) values ('Engineering', 100);
insert into category (name, product_id) values ('Accounting', 67);
insert into category (name, product_id) values ('Legal', 16);
insert into category (name, product_id) values ('Engineering', 12);
insert into category (name, product_id) values ('Support', 59);
insert into category (name, product_id) values ('Marketing', 46);
insert into category (name, product_id) values ('Legal', 72);
insert into category (name, product_id) values ('Business Development', 50);
insert into category (name, product_id) values ('Support', 42);
insert into category (name, product_id) values ('Marketing', 88);
insert into category (name, product_id) values ('Sales', 86);
insert into category (name, product_id) values ('Services', 27);
insert into category (name, product_id) values ('Accounting', 89);
insert into category (name, product_id) values ('Accounting', 41);
insert into category (name, product_id) values ('Sales', 45);
insert into category (name, product_id) values ('Sales', 20);
insert into category (name, product_id) values ('Accounting', 58);
insert into category (name, product_id) values ('Business Development', 96);
insert into category (name, product_id) values ('Human Resources', 57);
insert into category (name, product_id) values ('Accounting', 80);
insert into category (name, product_id) values ('Business Development', 68);
insert into category (name, product_id) values ('Product Management', 8);
insert into category (name, product_id) values ('Business Development', 29);
insert into category (name, product_id) values ('Training', 52);
insert into category (name, product_id) values ('Engineering', 37);
insert into category (name, product_id) values ('Support', 60);
insert into category (name, product_id) values ('Research and Development', 51);
insert into category (name, product_id) values ('Support', 17);
insert into category (name, product_id) values ('Sales', 2);
insert into category (name, product_id) values ('Services', 34);
insert into category (name, product_id) values ('Training', 40);
insert into category (name, product_id) values ('Marketing', 97);
insert into category (name, product_id) values ('Human Resources', 16);
insert into category (name, product_id) values ('Research and Development', 9);
insert into category (name, product_id) values ('Marketing', 26);
insert into category (name, product_id) values ('Services', 86);
insert into category (name, product_id) values ('Support', 17);
insert into category (name, product_id) values ('Legal', 48);
insert into category (name, product_id) values ('Product Management', 17);
insert into category (name, product_id) values ('Product Management', 46);
insert into category (name, product_id) values ('Research and Development', 60);
insert into category (name, product_id) values ('Legal', 53);
insert into category (name, product_id) values ('Product Management', 58);
insert into category (name, product_id) values ('Training', 72);
insert into category (name, product_id) values ('Services', 97);
insert into category (name, product_id) values ('Product Management', 74);
insert into category (name, product_id) values ('Services', 63);
insert into category (name, product_id) values ('Research and Development', 50);
insert into category (name, product_id) values ('Business Development', 31);
insert into category (name, product_id) values ('Training', 43);
insert into category (name, product_id) values ('Training', 49);
insert into category (name, product_id) values ('Sales', 73);
insert into category (name, product_id) values ('Research and Development', 77);
insert into category (name, product_id) values ('Accounting', 88);
insert into category (name, product_id) values ('Business Development', 59);
insert into category (name, product_id) values ('Engineering', 6);
insert into category (name, product_id) values ('Engineering', 21);
insert into category (name, product_id) values ('Business Development', 75);
insert into category (name, product_id) values ('Sales', 62);
insert into category (name, product_id) values ('Product Management', 60);
insert into category (name, product_id) values ('Product Management', 12);
insert into category (name, product_id) values ('Support', 92);
insert into category (name, product_id) values ('Engineering', 56);
insert into category (name, product_id) values ('Services', 82);
insert into category (name, product_id) values ('Business Development', 44);
insert into category (name, product_id) values ('Legal', 38);
insert into category (name, product_id) values ('Services', 40);
insert into category (name, product_id) values ('Business Development', 87);
insert into category (name, product_id) values ('Human Resources', 43);
insert into category (name, product_id) values ('Human Resources', 63);
insert into category (name, product_id) values ('Business Development', 42);
insert into category (name, product_id) values ('Product Management', 8);
insert into category (name, product_id) values ('Engineering', 86);
insert into category (name, product_id) values ('Training', 47);
insert into category (name, product_id) values ('Business Development', 30);
insert into category (name, product_id) values ('Accounting', 4);
insert into category (name, product_id) values ('Human Resources', 30);
insert into category (name, product_id) values ('Business Development', 69);
insert into category (name, product_id) values ('Marketing', 47);
insert into category (name, product_id) values ('Engineering', 26);
insert into category (name, product_id) values ('Legal', 82);
insert into category (name, product_id) values ('Legal', 66);
insert into category (name, product_id) values ('Business Development', 16);
insert into category (name, product_id) values ('Accounting', 6);
insert into category (name, product_id) values ('Services', 90);
insert into category (name, product_id) values ('Research and Development', 75);
insert into category (name, product_id) values ('Accounting', 48);
insert into category (name, product_id) values ('Marketing', 75);
insert into category (name, product_id) values ('Legal', 6);
insert into category (name, product_id) values ('Marketing', 36);
insert into category (name, product_id) values ('Sales', 99);
insert into category (name, product_id) values ('Product Management', 69);
insert into category (name, product_id) values ('Research and Development', 47);
insert into category (name, product_id) values ('Engineering', 19);
insert into category (name, product_id) values ('Accounting', 38);
insert into category (name, product_id) values ('Services', 9);
insert into category (name, product_id) values ('Engineering', 63);
insert into category (name, product_id) values ('Research and Development', 16);
insert into category (name, product_id) values ('Business Development', 24);
insert into category (name, product_id) values ('Training', 90);
insert into category (name, product_id) values ('Sales', 14);
insert into category (name, product_id) values ('Business Development', 100);
insert into category (name, product_id) values ('Research and Development', 34);
insert into category (name, product_id) values ('Product Management', 89);
insert into category (name, product_id) values ('Legal', 33);
insert into category (name, product_id) values ('Accounting', 41);
insert into category (name, product_id) values ('Training', 59);
insert into category (name, product_id) values ('Engineering', 61);
insert into category (name, product_id) values ('Business Development', 100);
insert into category (name, product_id) values ('Support', 69);
insert into category (name, product_id) values ('Research and Development', 16);
insert into category (name, product_id) values ('Business Development', 67);
insert into category (name, product_id) values ('Support', 64);
insert into category (name, product_id) values ('Product Management', 82);
insert into category (name, product_id) values ('Marketing', 34);
insert into category (name, product_id) values ('Human Resources', 12);
insert into category (name, product_id) values ('Marketing', 38);
insert into category (name, product_id) values ('Accounting', 6);
insert into category (name, product_id) values ('Marketing', 67);
insert into category (name, product_id) values ('Sales', 68);
insert into category (name, product_id) values ('Support', 42);
insert into category (name, product_id) values ('Engineering', 31);
insert into category (name, product_id) values ('Product Management', 30);
insert into category (name, product_id) values ('Accounting', 20);
insert into category (name, product_id) values ('Research and Development', 19);
insert into category (name, product_id) values ('Accounting', 14);
insert into category (name, product_id) values ('Support', 97);
insert into category (name, product_id) values ('Support', 94);
insert into category (name, product_id) values ('Business Development', 60);
insert into category (name, product_id) values ('Legal', 4);
insert into category (name, product_id) values ('Business Development', 15);
insert into category (name, product_id) values ('Product Management', 54);
insert into category (name, product_id) values ('Legal', 11);
insert into category (name, product_id) values ('Engineering', 24);
insert into category (name, product_id) values ('Sales', 95);
insert into category (name, product_id) values ('Human Resources', 92);
insert into category (name, product_id) values ('Legal', 61);
insert into category (name, product_id) values ('Accounting', 79);

update shop set product_count = (select count(*) from product where shop_id = shop.id),
category_count = (select count( distinct name ) from category where product_id in (select id from product where shop_id = shop.id));